spring.application.name=video-processing-tracker

#aws dynamo
#aws.dynamodb.endpoint=http://localhost:8000
aws.dynamodb.endpoint=https://dynamodb.us-east-1.amazonaws.com
aws.dynamodb.create-tables=false
aws.region=us-east-1
