apiVersion: v1
kind: Service
metadata:
  name: app-service-video-processing-tracker
spec:
  selector:
    app: video-processing-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer